name: Bug report
description: Create a report to help improve WSA Sideloader
title: "[BUG]"
labels: bug

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Include screenshots if possible.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Include steps to reproduce the behaviour.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: source
    attributes:
      label: Download source
      description: Where did you download WSA Sideloader from?
      options:
        - GitHub
        - Microsoft Store
        - PyPi
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Application version
      description: You can find the application version by pressing About WSA Sideloader on the main window.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: For GitHub and MS Store versions, please copy and paste the contents of the log file which can be found at %appdata%/WSA_Sideloader.launch.pyw.log
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
