theme: jekyll-theme-cayman
title: WSA Sideloader
description: Easily sideload Android apps on Windows Subsystem for Android on Windows 11
logo_url: https://github.com/infinitepower18/WSA-Sideloader/raw/main/docs/favicon.png
